name: create-gen2

on:
  workflow_dispatch:
    
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: az spring create and az spring app create
        uses: Azure/cli@v1
        with:
          azcliversion: 2.46.0
          inlineScript: |
            az extension add --name containerapp --upgrade
            az provider register --namespace Microsoft.App
            az provider register --namespace Microsoft.OperationalInsights
            az containerapp env create -n "tanzu-tv-asa" -g resource-group tanzu-tv -l "eastus"
            az extension add --source https://ascprivatecli.blob.core.windows.net/cli-extension/spring-1.1.11-py3-none-any.whl --upgrade --yes
            az provider register --namespace Microsoft.AppPlatform
            az spring create -g tanzu-tv -n tanzu-tv-asa-app --managed-environment "$(az containerapp env show -n tanzu-tv-asa -g tanzu-tv --query id -o tsv)" --sku standardGen2 -l "eastus"
            az spring app create --resource-group tanzu-tv --service tanzu-tv-asa-app --name image-service --cpu 1 --memory 2Gi --assign-endpoint true