name: create-gen2

on:
  workflow_dispatch:
    
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Checkout master
        uses: actions/checkout@v3
      - name: build image
        run: ./mvnw clean package
      - name: az spring app deploy
        uses: Azure/cli@v1
        with:
          azcliversion: 2.46.0
          inlineScript: |
            az extension add --name containerapp --upgrade
            az extension add --source https://ascprivatecli.blob.core.windows.net/cli-extension/spring-1.1.11-py3-none-any.whl --upgrade --yes
            az spring app deploy --resource-group tanzu-tv --service tanzu-tv-asa --name image-service --artifact-path ./target/image-0.0.1-SNAPSHOT.jar --runtime-version Java_17 --jvm-options '-Xms1024 -Xmx2048m'
            az spring app scale --resource-group tanzu-tv --service tanzu-tv-asa --name image-service --min-instance-count 0 --max-instance-count 2