name: destroy-log-analytics

on:
  workflow_dispatch:
    
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: az monitor log-analytics workspace delete
        uses: Azure/cli@v1
        with:
          azcliversion: 2.46.0
          inlineScript: |
            az monitor log-analytics workspace delete --force true -resource-group tanzu-tv --yes