name: destroy-gen2

on:
  workflow_dispatch:
    
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: az containerapp env delete
        uses: Azure/cli@v1
        with:
          azcliversion: 2.46.0
          inlineScript: |
            az extension add --name containerapp --upgrade
            az provider register --namespace Microsoft.App
            az provider register --namespace Microsoft.OperationalInsights
            az spring app destroy --resource-group tanzu-tv --service tanzu-tv-asa --name image-service
            az spring create --resource-group tanzu-tv --name tanzu-tv-asa-app --managed-environment $(az containerapp env show --name tanzu-tv-asa --resource-group tanzu-tv --query id -o tsv) --location "eastus"
            az containerapp env delete --name "tanzu-tv-asa" --resource-group tanzu-tv --yes
            az monitor log-analytics workspace delete --name $(az monitor log-analytics workspace list --query [0].name -o tsv) --force true --resource-group tanzu-tv --yes